---
name: xt Full Test Matrix
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  stable-msrv-test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-22.04, macos-12, windows-2022]
        toolchain: [stable, 1.61.0]
    runs-on: ${{ matrix.runner }}
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: rustup toolchain install
      run: |
        rustup set profile minimal
        rustup toolchain install ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustc --version
    - name: cargo test
      run: cargo test
  linux-miri-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install nightly --component miri --allow-downgrade
        rustup default nightly
        rustc --version
    - name: cargo miri test
      run: cargo miri test
