---
name: xt Full Test Matrix
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  unix-stable-msrv-test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-22.04, macos-12]
        toolchain: [stable, 1.61.0]
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustc --version
    - name: cargo test
      run: cargo test
  # TODO: Integration tests currently fail on Windows due to LF vs. CRLF
  # inconsistency. Need to find a solution for this, which sadly will be tough
  # since I don't have a Windows machine of my own right now.
  windows-stable-msrv-build:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, 1.61.0]
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustc --version
    - name: cargo build
      run: cargo build
  linux-miri-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install nightly --component miri --allow-downgrade
        rustup default nightly
        rustc --version
    - name: cargo miri test
      run: cargo miri test
