---
name: xt Full Test Matrix
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
jobs:
  stable-msrv-test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, macos-14, windows-2022]
        toolchain: [stable, 1.70.0]
    runs-on: ${{ matrix.runner }}
    steps:
    - name: git checkout
      uses: actions/checkout@v4
    - name: rustup toolchain install
      run: |
        rustup set profile minimal
        rustup toolchain install ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustc --version
    - name: cargo check
      run: cargo check
    - name: cargo test
      run: cargo test
  linux-miri-test:
    runs-on: ubuntu-24.04
    steps:
    - name: git checkout
      uses: actions/checkout@v4
    - name: rustup toolchain install
      run: |
        rustup set profile minimal
        rustup toolchain install nightly --component miri --allow-downgrade
        rustup default nightly
        rustc --version
    - name: download nextest
      run: curl -LsSf https://get.nexte.st/0.9/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: cargo miri test
      run: cargo miri nextest run -j num-cpus
