---
name: xt Windows Tests
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  windows-stable-msrv-test:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, 1.61.0]
    runs-on: windows-2022
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: rustup toolchain install
      run: |
        rustup set profile minimal
        rustup toolchain install ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustc --version
    - name: cargo test
      run: cargo test
